ESP_ROOT=$(HOME)/projects/pi/arduino-build/esp8266
SKETCH=rainmachine-esp8266.ino
BUILD_DIR=$(HOME)/projects/pi/rainmachine/rainmachine-esp8266/build

include $(HOME)/projects/pi/arduino-build/makeEspArduino/makeEspArduino.mk
